services:
  db:
    image: postgres:15-alpine
    container_name: alkahfi_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alkahfi_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      # target: dev  <--- BARIS INI DIHAPUS
    container_name: alkahfi_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/alkahfi_db
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

volumes:
  pgdata:
